# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100  # Hz

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scara_controller:
  ros__parameters:
    joints:
      - Brazo1_link_joint
      - Brazo2_link_joint
      - Brazo3_link_joint
      - Brazo4_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
gripper_controller:
  ros__parameters:
    joints:
      - Gripper1_link_joint
      - Gripper2_link_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true